const formations=[
"4-3-3","4-4-2","4-2-3-1","4-3-2-1","4-2-2-2","4-1-2-1-2","4-1-3-2","4-3-1-2","4-4-1-1",
"3-4-3","3-4-1-2","3-5-2","3-4-2-1","5-3-2","5-2-3","5-4-1","5-2-1-2","4-5-1","4-2-4","4-3-3 False 9","2-3-5"
];
const players=[
["Erling Haaland",91,"ST"],["Kylian Mbappe",91,"ST"],["Vinicius Jr",90,"LW"],["Jude Bellingham",90,"CM"],["Rodri",90,"CDM"],["Mohamed Salah",90,"RW"],["Kevin De Bruyne",89,"CM"],["Harry Kane",89,"ST"],["Lamine Yamal",89,"RW"],["Virgil van Dijk",89,"CB"],["Alisson",89,"GK"],["Thibaut Courtois",89,"GK"],["Bukayo Saka",88,"RW"],["Son Heung-min",88,"LW"],["William Saliba",88,"CB"],["Federico Valverde",88,"CM"],["Bernardo Silva",88,"CAM"],["Martin Odegaard",87,"CAM"],["Achraf Hakimi",87,"RB"],["Theo Hernandez",87,"LB"],["Antonio Rudiger",87,"CB"],["Declan Rice",87,"CDM"],["Lautaro Martinez",87,"ST"],["Pedri",86,"CM"],["Phil Foden",86,"CAM"],["Ruben Dias",86,"CB"],["Mike Maignan",86,"GK"],["Trent Alexander-Arnold",85,"RB"],["Nuno Mendes",85,"LB"],["Victor Osimhen",85,"ST"],["Rafael Leao",85,"LW"],["Cole Palmer",85,"CAM"],["Gabriel",84,"CB"],["Enzo Fernandez",84,"CM"],["Ousmane Dembele",84,"RW"],["Bruno Fernandes",84,"CAM"],["Gianluigi Donnarumma",84,"GK"],["Mikel Merino",82,"CM"],["Gabriel Martinelli",82,"LW"],["Jonathan Tah",82,"CB"],["Benjamin Pavard",81,"RB"],["Diogo Costa",81,"GK"],["Nicolas Jackson",80,"ST"],["Conor Gallagher",79,"CM"],["Lisandro Martinez",79,"CB"]
].map((p,i)=>({id:i+1,name:p[0],ovr:p[1],pos:p[2]}));

let state=JSON.parse(localStorage.getItem("fcdraft_state")||"null")||{coins:1000,owned:[],drafts:0,wins:0,losses:0,history:[],formation:null,squad:{}};
let selectedDiff="Beginner", currentPos=null;

const reward={Beginner:50,Amateur:75,"Semi-Pro":100,Professional:150,"World Class":225,Legendary:350};
const difficultyPower={Beginner:55,Amateur:65,"Semi-Pro":72,Professional:78,"World Class":84,Legendary:89};

function save(){localStorage.setItem("fcdraft_state",JSON.stringify(state));updateHeader();}
function updateHeader(){document.querySelector("#coins").textContent=state.coins.toLocaleString();document.querySelector("#homePlayers").textContent=state.owned.length;document.querySelector("#homeDrafts").textContent=state.drafts;document.querySelector("#homeWins").textContent=state.wins;document.querySelector("#homeRating").textContent=clubRating()||0}
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.querySelector("#"+id).classList.add("active");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));if(id==="market")renderMarket();if(id==="club")renderClub();if(id==="matches")renderHistory();updateHeader()}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>showPage(b.dataset.page));

function tier(ovr){if(ovr>=90)return"Very Rare";if(ovr===89)return"Epic";if(ovr>=85)return"Rare";if(ovr>=75)return"Gold";if(ovr>=65)return"Silver";return"Bronze"}
function candidates(pos){let eligible=players.filter(p=>p.pos===pos);let owned=players.filter(p=>state.owned.includes(p.id)&&p.pos===pos);eligible=[...eligible,...owned];let pool=[...eligible];while(pool.length<3)pool.push(...players.filter(p=>p.pos!==pos).slice(0,3));pool.sort(()=>Math.random()-.5);return pool.slice(0,3)}
function init(){document.querySelector("#formations").innerHTML=formations.map(f=>`<button class="formation" onclick="selectFormation('${f}')"><b>${f}</b><span>Balanced squad setup</span></button>`).join("");updateHeader();renderHistory()}
function selectFormation(f){state.formation=f;state.squad={};currentPos=null;document.querySelector("#formationPicker").classList.add("hidden");document.querySelector("#draftArea").classList.remove("hidden");document.querySelector("#draftStatus").textContent=f;renderPitch()}
function positionsFor(f){let [d,m,a]=f.split("-").map(Number);if(f==="2-3-5")return [["GK",50,92],["LB",30,77],["CB",50,80],["RB",70,77],["LM",28,56],["CM",50,57],["RM",72,56],["LW",18,27],["ST",50,22],["RW",82,27],["CF",50,38]];let arr=[["GK",50,92]];const back=d===3?[30,50,70]:d===5?[18,34,50,66,82]:[24,50,76];back.forEach((x,i)=>arr.push([i===0&&d===5?"LWB":i===back.length-1&&d===5?"RWB":"DEF",x,78]));const mids=m===5?[15,33,50,67,85]:m===4?[20,40,60,80]:m===3?[25,50,75]:[30,70];mids.forEach((x)=>arr.push(["MID",x,55]));const fwd=a===1?[["ST",50,25]]:a===2?[["LW",35,25],["ST",65,25]]:[["LW",20,25],["ST",50,22],["RW",80,25]]);return arr.concat(fwd)}
function renderPitch(){let ps=positionsFor(state.formation);document.querySelector("#pitch").innerHTML=ps.map((p,i)=>{let key=p[0]+i,filled=state.squad[key];return `<button class="slot ${filled?"filled":""}" style="left:${p[1]}%;top:${p[2]}%" onclick="choosePos('${key}','${p[0]}')">${filled?players.find(x=>x.id===filled).name.split(" ").pop():"+"}<small>${p[0]}</small></button>`}).join("")}
function choosePos(key,pos){currentPos=key;document.querySelector("#choicePosition").textContent=`Choose ${pos}`;let list=candidates(pos);document.querySelector("#choiceList").innerHTML=list.map(p=>`<button class="choice" onclick="pick(${p.id})"><div class="avatar">${p.ovr}</div><div class="info"><b>${p.name}</b><span>${p.pos} · ${tier(p.ovr)}</span></div><div class="ovr">${p.ovr}</div></button>`).join("")}
function pick(id){if(!currentPos)return;state.squad[currentPos]=id;save();renderPitch();document.querySelector("#choiceList").innerHTML=`<div class="empty">Player selected. Choose another position.</div>`;if(Object.keys(state.squad).length===positionsFor(state.formation).length){state.drafts++;state.owned=[...new Set([...state.owned,...Object.values(state.squad)])];save();document.querySelector("#choiceList").innerHTML=`<div class="empty"><b>Draft complete!</b><br>Your squad is ready for a match.</div><button class="primary wide" onclick="showPage('matches')">Play Match →</button>`}}
function resetDraft(){state.formation=null;state.squad={};currentPos=null;document.querySelector("#formationPicker").classList.remove("hidden");document.querySelector("#draftArea").classList.add("hidden")}
function clubRating(){let ids=Object.values(state.squad);if(!ids.length)return state.owned.length?Math.round(state.owned.reduce((s,id)=>s+(players.find(p=>p.id===id)?.ovr||0),0)/state.owned.length):0;return Math.round(ids.reduce((s,id)=>s+(players.find(p=>p.id===id)?.ovr||0),0)/ids.length)}
function card(p,market=false){let owned=state.owned.includes(p.id);let price=Math.max(100,(p.ovr-60)*35);return `<div class="player-card"><div class="player-top"><span class="tier">${tier(p.ovr)}</span><b>${p.ovr}</b></div><div class="player-name">${p.name}</div><div class="muted">${p.pos} · OVR ${p.ovr}</div>${market?`<button class="buy" ${owned||state.coins<price?"disabled":""} onclick="buy(${p.id})">${owned?"Owned":"Buy · 🪙 "+price}</button>`:""}</div>`}
function renderMarket(){document.querySelector("#marketGrid").innerHTML=players.map(p=>card(p,true)).join("")}
function buy(id){let p=players.find(x=>x.id===id),price=Math.max(100,(p.ovr-60)*35);if(!p||state.owned.includes(id)||state.coins<price)return;state.coins-=price;state.owned.push(id);save();renderMarket();renderClub()}
function renderClub(){document.querySelector("#clubGrid").innerHTML=state.owned.length?state.owned.map(id=>card(players.find(p=>p.id===id))).join(""):`<div class="panel">No players yet. Complete a draft or visit the market.</div>`}
document.querySelectorAll(".diff").forEach(b=>b.onclick=()=>{document.querySelectorAll(".diff").forEach(x=>x.classList.remove("active"));b.classList.add("active");selectedDiff=b.dataset.diff});
function playMatch(){if(!Object.keys(state.squad).length){document.querySelector("#matchResult").innerHTML='<div class="result">Complete a draft first.</div>';return}let rating=clubRating(),power=difficultyPower[selectedDiff],your=Math.max(1,Math.round((rating+Math.random()*14)-power*.25)),opp=Math.max(0,Math.round(power+Math.random()*13));let win=your>=opp;if(win){state.wins++;state.coins+=reward[selectedDiff]}else state.losses++;state.history.unshift({diff:selectedDiff,your,opp,win,coins:win?reward[selectedDiff]:0});state.history=state.history.slice(0,10);save();document.querySelector("#matchResult").innerHTML=`<div class="result"><div>${win?"🏆 YOU WIN":"MATCH RESULT"}</div><div class="score">${your} - ${opp}</div><div class="${win?"win":"loss"}">${win?"+"+reward[selectedDiff]+" coins":"Defeat — try again"}</div></div>`;renderHistory()}
function renderHistory(){document.querySelector("#historyList").innerHTML=state.history.length?state.history.map(h=>`<div class="history-row"><span>${h.diff}</span><b class="${h.win?"win":"loss"}">${h.your}-${h.opp}</b><span>${h.win?"+"+h.coins:"—"}</span></div>`).join(""):`<div class="muted">No matches played yet.</div>`}
init();